version: '3.7'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    ports:
      - "homarr_port:7575"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
      - ./homarr/data:/data

  dashdot:
    container_name: dashdot
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - 'dash_port:3001'
    volumes:
      - /:/mnt/host:ro
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'

  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "gitea_html_port:3000"
      - "gitea_ssh_port:2999"

  gitea-runner:
    container_name: gitea-runner
    image: gitea/act_runner:nightly
    restart: unless-stopped
    environment:
      GITEA_INSTANCE_URL: "http://gitea:3000"
      GITEA_RUNNER_REGISTRATION_TOKEN: "runner-token-here"
      GITEA_RUNNER_NAME: "runner-1"
      GITEA_RUNNER_LABELS: "runner-1-docker"
      GITEA_INSTANCE_INSECURE: "true"
    volumes:
      - ./gitea-runner/data:/data
      - /var/run/docker.sock:/var/run/docker.sock


  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "watchtower_port:8080"
